version: 1.0.{build}

before_build:
  - nuget restore GroceryImport/GroceryImport.sln

build:
  project: GroceryImport/GroceryImport.sln
  verbosity: detailed

test_script:
  - vstest.console /logger:Appveyor GroceryImport\GroceryImport.Core.Tests\bin\Debug\netcoreapp3.1\GroceryImport.Core.Tests.dll

on_finish:
  - sh: |
      find "$APPVEYOR_BUILD_FOLDER" -type f -name '**\TestResults\*.xml' -print0 | xargs -0 -I '{}' curl -F 'file=@{}' "https://ci.appveyor.com/api/testresults/mstest/$APPVEYOR_JOB_ID"